### ISSUE TITLE
Where can I order the ribbon?

### ISSUE THREAD

**Issue by iVirtualPlays** [dshadoff/PCE_FRAM_adapter#1]
I see no link for ordering the ribbon. I also cannot find it on OSH Park.

**Comment by dshadoff** [comment]
I am not selling it, nor have I filed the designs with any PCB manufacturing facility; however, the gerber files are included in this repository, so that they can be sent to any PC board factory which suits you (the surface-mount version uses "Flex PCB").

OSHPark is probably a good place, since they have a reasonably low cost for small quantities for flex PCBs (while the Chinese factories are very cost-effective for regular PCBs, they aren't cost-effective for small quantities of flex PCBs).

For the gerber files you would need to submit, they can be found here:
https://github.com/dshadoff/PCE_FRAM_adapter/tree/master/FRAM-SOIC
...the file is "FRAM-SOIC.zip"

**Comment by iVirtualPlays** [comment]
Thanks for quick reply, do you know what the two resistors are A11 and A12? And how to wire up a bank switch? Will i need a 3-way toggle switch along with some pull-up resistors?

**Comment by dshadoff** [comment]
the two resistors are for pull-up, in case the inputs at A11 and A12 are either disconnected or unreliable.  47Kohm, 0603 surface-mount.  If you can guarantee stable logic signals at the A11 and A12 inputs, then they are not needed.

To hook up a bank switch, you'll need to figure out whether you need all 4 banks or not - if you do, then you'll need to find a way to apply the 4 different logic combinations to the A11/A12 pins:  { low/low, low/high, high/low, high/high }.

If you only need two banks, then an SPST switch may suffice (plus the pullups mentioned above): the SPST switch can connect one of (A11 or A12) to ground (for low) or leave it open (for high, due to the pullup).

**Comment by LobAnovich** [comment]
In the project files for making the adapter board (FRAM-SOP_rev_B.zip), it is indicated that the boards are made of testolite or flexible boards?
When placing an order, do I need to additionally specify (select) "flexible PCB" or is this information included in the manufacturing files?

**Comment by dshadoff** [comment]
> In the project files for making the adapter board (FRAM-SOP_rev_B.zip), it is indicated that the boards are made of testolite or flexible boards?
> When placing an order, do I need to additionally specify (select) "flexible PCB" or is this information included in the manufacturing files?

That board - replacing a surface-mount memory chip in the Duo - is intended to be a flexible PCB.  (I'm not familiar with the term "testolite", but they are generally made using polyimide)

I don't believe that EAGLE has the ability to specify that type of information in the gerber file outputs, so you should specify "flexible PCB" at the board maker when you order.

**Comment by LobAnovich** [comment]
> > In the project files for making the adapter board (FRAM-SOP_rev_B.zip), it is indicated that the boards are made of testolite or flexible boards?
> > When placing an order, do I need to additionally specify (select) "flexible PCB" or is this information included in the manufacturing files?
> 
> That board - replacing a surface-mount memory chip in the Duo - is intended to be a flexible PCB. (I'm not familiar with the term "testolite", but they are generally made using polyimide)
> 
> I don't believe that EAGLE has the ability to specify that type of information in the gerber file outputs, so you should specify "flexible PCB" at the board maker when you order.

Yes, I misspelled it. I meant a textolite (non-flexible) PCB. I sent a request to one of the small Chinese manufacturers (I can't order from large manufacturers), and I'm waiting for a response.
